{% set data = load_setup_py_data() %}
{% set version = "1.2.2" %}

package:
  name: mako
  version: "{{ version }}"

source:
  git_url: https://github.com/ramellose/mako.git

requirements:
  host:
    - python >=3.5
    - setuptools
    - pbr
  run:
    - python >=3.5
    - numpy >=1.15.0
    - scipy >=1.4.1
    - h5py >=2.9.0
    - neo4j-python-driver >=4.2.1
    - networkx ==2.4
    - pandas >=1.1.5
    - pbr
    - pyyaml
    - biom-format
    - psutil
    - requests
    - Cython
    - manta
    - anuran

about:
  home: https://github.com/ramellose/mako
  license: Apache 2.0
  license_file: LICENSE
  summary: "Cataloguing microbial associations via Neo4j"